# Generated by Django 2.0.2 on 2019-07-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriessquads',
            name='Squad_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.Players'),
        ),
    ]
