# Generated by Django 2.0.2 on 2019-07-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_team', '0002_auto_20190723_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerpoints',
            name='fours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='playerpoints',
            name='runs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='playerpoints',
            name='total_points',
            field=models.FloatField(),
        ),
    ]
