# Generated by Django 2.0.2 on 2019-07-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_team', '0003_auto_20190724_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteampoints',
            name='points',
            field=models.FloatField(),
        ),
    ]
