# Generated by Django 2.0.2 on 2019-08-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0005_users_contests'),
        ('create_team', '0005_privatecontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(default='', max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.Users')),
            ],
        ),
        migrations.AddField(
            model_name='leaguemembers',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_team.Leagues'),
        ),
        migrations.AddField(
            model_name='leaguemembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.Users'),
        ),
    ]
