# Generated by Django 2.1.2 on 2019-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_users_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
    ]
