# Generated by Django 2.0.2 on 2019-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0003_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='credit',
            field=models.FloatField(default=None),
        ),
    ]
