# Generated by Django 2.0.2 on 2019-07-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0004_players_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contests',
            field=models.TextField(default='[]'),
        ),
    ]
