# Generated by Django 2.0.2 on 2019-09-03 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0005_users_contests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='contests',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='noName', max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=250, validators=[django.core.validators.MaxLengthValidator(limit_value=8, message='password must be at least 8 characters long')]),
        ),
    ]
