# Generated by Django 2.1.2 on 2019-09-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0007_auto_20190903_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='contests',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
