# Generated by Django 2.1.2 on 2019-09-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0008_auto_20190904_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contests',
            field=models.CharField(default='', max_length=100),
        ),
    ]
